### PR TITLE
Fixes thread safety issues in android code. closes #161

### LINKED ISSUE #161: Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
How to fix this problem? 

```
E/flutter (29195): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E/flutter (29195): 	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
E/flutter (29195): 	at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:570)
E/flutter (29195): 	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:351)
E/flutter (29195): 	at javax.crypto.Cipher.doFinal(Cipher.java:1741)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:91)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:163)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:144)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$300(FlutterSecureStoragePlugin.java:29)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:197)
E/flutter (29195): 	at java.lang.Thread.run(Thread.java:764)
E/flutter (29195): , null)
```

### LINKED ISSUE #163: WRONG_FINAL_BLOCK_LENGTH
@mogol We are encountering this error on production, but unfortunately i am not able to reproduce it.

```
javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:365)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(Unknown Source:32)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$400(Unknown Source:11)
                                                                  access$500
                                                                  decodeRawValue
                                                                  ensureInitStorageCipher
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(Unknown Source:7)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(Unknown Source:0)
                                                                  access$100
                                                                  access$200
                                                                  access$300
                                                                  addPrefixToKey
                                                                  deleteAll
                                                                  getKeyFromCall
                                                                  initInstance
                                                                  write
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(Unknown Source:134)
	at java.lang.Thread.run(Thread.java:929)
```

What relevant information would you like me to include?

### PR DESCRIPTION
**Pull request by koskimas**
Before, every call from flutter was executed in a separate thread and only the ensureInitStorageCipher was synchronized. All other operations were run without any synchronization. Most of the code is not thread safe, which caused multiple problems when two or more method calls happened to run at the same time.

This PR fixes the thread safety issues by using a single worker thread in which all calls from flutter are executed.

This closes #161 but probably also fixes #163.

### CODE REVIEW

File: android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java [hunk 1]
```diff
@@ -59,25 +65,14 @@ public void initInstance(BinaryMessenger messenger, Context context) {
...
 
-    /**
-     * This must be run in a separate Thread from an async method to avoid hanging UI thread on
-     * live devices in release mode.
-     * The most convenient place for that appears to be onMethodCall().
-     */
     private void ensureInitStorageCipher() {
-        // Check to avoid unnecessary entry into the synchronized block.
         if (storageCipher == null) {
-            synchronized (this) {
```
Comment (mogol) [inline android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java:70]: Why do you remove this sync point ?

Comment (koskimas) [reply android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java:70]: Because there's only one thread from which the method is ever called. No need to synchronize. That's the whole point of this change.

**Comment by mogol** [comment]
@koskimas thanks
Let's give it a shot. Your repro case works (or doesn't work) perfectly.

**Comment by koskimas** [comment]
Thank you for reviewing and merging this so quickly! And thanks again for your work on this library.

**Comment by mogol** [comment]
I really hope it resolves this long running issues, as it was completely mystery for me for a while 🙏 really appreciate your contribution
